# BetterCapes Configuration
# This plugin allows players to steal skins and capes from other players
# Commands:
# /identity <player> - Change your skin and name to match another player
# /stealcape <player> - Steal a cape from another player (if they have one)
